// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using Hephaisto.Agent.Persistence;

#nullable disable

namespace Hephaisto.Agent.Persistence.Migrations
{
    [DbContext(typeof(HephaistoDbContext))]
    [Migration("20260828060909_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hephaisto.Agent.Persistence.AgentModeRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("text")
                        .HasColumnName("changed_by");

                    b.Property<string>("LatchReason")
                        .HasColumnType("text")
                        .HasColumnName("latch_reason");

                    b.Property<DateTimeOffset?>("LatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("latched_at");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mode");

                    b.Property<bool>("RunawayLatched")
                        .HasColumnType("boolean")
                        .HasColumnName("runaway_latched");

                    b.HasKey("Id")
                        .HasName("pk_agent_mode");

                    b.ToTable("agent_mode", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "singleton",
                            ChangedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ChangedBy = "hephaisto/system",
                            Mode = "Observe",
                            RunawayLatched = false
                        });
                });

            modelBuilder.Entity("Hephaisto.Agent.Persistence.LlmBudgetBreach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<DateTimeOffset>("HourBucket")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hour_bucket");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.HasKey("Id")
                        .HasName("pk_llm_budget_breaches");

                    b.HasIndex("At")
                        .IsDescending()
                        .HasDatabaseName("ix_llm_budget_breaches_at");

                    b.HasIndex("HourBucket", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_llm_budget_breaches_hour_bucket_kind");

                    b.ToTable("llm_budget_breaches", (string)null);
                });

            modelBuilder.Entity("Hephaisto.Agent.Persistence.LlmUsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<decimal>("CostUsd")
                        .HasColumnType("numeric(14,6)")
                        .HasColumnName("cost_usd");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("input_tokens");

                    b.Property<Guid?>("InvestigationId")
                        .HasColumnType("uuid")
                        .HasColumnName("investigation_id");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("output_tokens");

                    b.HasKey("Id")
                        .HasName("pk_llm_usage");

                    b.HasIndex("At")
                        .IsDescending()
                        .HasDatabaseName("ix_llm_usage_at");

                    b.HasIndex("IncidentId", "At")
                        .HasDatabaseName("ix_llm_usage_incident_id_at");

                    b.ToTable("llm_usage", (string)null);
                });

            modelBuilder.Entity("Hephaisto.Agent.Persistence.WorkloadActionLock", b =>
                {
                    b.Property<string>("WorkloadKey")
                        .HasColumnType("text")
                        .HasColumnName("workload_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("WorkloadKey")
                        .HasName("pk_workload_action_locks");

                    b.ToTable("workload_action_locks", (string)null);
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.ActionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InvestigationId")
                        .HasColumnType("uuid")
                        .HasColumnName("investigation_id");

                    b.Property<bool>("NoActionRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("no_action_required");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_action_plans");

                    b.HasIndex("InvestigationId")
                        .IsUnique()
                        .HasDatabaseName("ix_action_plans_investigation_id");

                    b.ToTable("action_plans", (string)null);
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.AgentAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActionPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("action_plan_id");

                    b.Property<string>("ApprovalReason")
                        .HasColumnType("text")
                        .HasColumnName("approval_reason");

                    b.Property<string>("ApprovalSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("approval_source");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text")
                        .HasColumnName("approved_by");

                    b.Property<string>("Arguments")
                        .HasColumnType("jsonb")
                        .HasColumnName("arguments");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("decision");

                    b.Property<string>("DecisionReasons")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("decision_reasons");

                    b.Property<bool>("DryRun")
                        .HasColumnType("boolean")
                        .HasColumnName("dry_run");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("EvidenceFindingIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence_finding_ids");

                    b.Property<DateTimeOffset?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<Guid?>("IsRollbackOf")
                        .HasColumnType("uuid")
                        .HasColumnName("is_rollback_of");

                    b.Property<string>("ModeAtExecution")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mode_at_execution");

                    b.Property<string>("Outcome")
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("PostState")
                        .HasColumnType("jsonb")
                        .HasColumnName("post_state");

                    b.Property<string>("PreState")
                        .HasColumnType("jsonb")
                        .HasColumnName("pre_state");

                    b.Property<string>("PredictedEffect")
                        .HasColumnType("text")
                        .HasColumnName("predicted_effect");

                    b.Property<string>("Risk")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("risk");

                    b.Property<string>("RollbackSpec")
                        .HasColumnType("jsonb")
                        .HasColumnName("rollback_spec");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_agent_actions");

                    b.HasIndex("ActionPlanId")
                        .HasDatabaseName("ix_agent_actions_action_plan_id");

                    b.HasIndex("ApprovedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_agent_actions_approved_at");

                    b.HasIndex("ExecutedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_agent_actions_executed_at");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("ix_agent_actions_incident_id");

                    b.ToTable("agent_actions", (string)null);
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActionId")
                        .HasColumnType("uuid")
                        .HasColumnName("action_id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Detail")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<Guid?>("InvestigationId")
                        .HasColumnType("uuid")
                        .HasColumnName("investigation_id");

                    b.Property<string>("SpanId")
                        .HasColumnType("text")
                        .HasColumnName("span_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("TraceId")
                        .HasColumnType("text")
                        .HasColumnName("trace_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("At")
                        .IsDescending()
                        .HasDatabaseName("ix_audit_events_at");

                    b.HasIndex("Detail")
                        .HasDatabaseName("ix_audit_events_detail_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Detail"), "gin");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("ix_audit_events_incident_id");

                    b.HasIndex("Type", "At")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_events_type_at");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.Evidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("excerpt");

                    b.Property<Guid>("FindingId")
                        .HasColumnType("uuid")
                        .HasColumnName("finding_id");

                    b.Property<string>("SourceUri")
                        .HasColumnType("text")
                        .HasColumnName("source_uri");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uuid")
                        .HasColumnName("step_id");

                    b.HasKey("Id")
                        .HasName("pk_evidence");

                    b.HasIndex("FindingId")
                        .HasDatabaseName("ix_evidence_finding_id");

                    b.HasIndex("StepId")
                        .HasDatabaseName("ix_evidence_step_id");

                    b.ToTable("evidence", (string)null);
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.EvidenceBlob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvestigationId")
                        .HasColumnType("uuid")
                        .HasColumnName("investigation_id");

                    b.HasKey("Id")
                        .HasName("pk_evidence_blobs");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_evidence_blobs_expires_at");

                    b.HasIndex("InvestigationId")
                        .HasDatabaseName("ix_evidence_blobs_investigation_id");

                    b.ToTable("evidence_blobs", (string)null);
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<string>("Hypothesis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hypothesis");

                    b.Property<Guid>("InvestigationId")
                        .HasColumnType("uuid")
                        .HasColumnName("investigation_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.HasKey("Id")
                        .HasName("pk_findings");

                    b.HasIndex("InvestigationId", "IsPrimary")
                        .HasDatabaseName("ix_findings_investigation_id_is_primary");

                    b.ToTable("findings", (string)null);
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.HumanFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<bool>("FalsePositive")
                        .HasColumnType("boolean")
                        .HasColumnName("false_positive");

                    b.Property<bool>("Helpful")
                        .HasColumnType("boolean")
                        .HasColumnName("helpful");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<bool?>("RootCauseCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("root_cause_correct");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("submitted_by");

                    b.HasKey("Id")
                        .HasName("pk_human_feedback");

                    b.HasIndex("At")
                        .HasDatabaseName("ix_human_feedback_at");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("ix_human_feedback_incident_id");

                    b.ToTable("human_feedback", (string)null);
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_key");

                    b.Property<string>("EscalationReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("escalation_reason");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("LastSignalAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_signal_at");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mode");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<DateTimeOffset?>("QuarantinedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("quarantined_until");

                    b.Property<string>("Resolution")
                        .HasColumnType("text")
                        .HasColumnName("resolution");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("SuppressionReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("suppression_reason");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_incidents");

                    b.HasIndex("CorrelationKey")
                        .HasDatabaseName("ix_incidents_correlation_key");

                    b.HasIndex("OpenedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_incidents_opened_at");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_incidents_state_open")
                        .HasFilter("state IN ('Detected', 'Triaging', 'Investigating', 'AwaitingApproval', 'Acting', 'Verifying', 'Escalated')");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.IncidentDigest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Digest")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("digest");

                    b.Property<string>("DigestHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("digest_hash");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("namespace");

                    b.Property<bool>("Resolved")
                        .HasColumnType("boolean")
                        .HasColumnName("resolved");

                    b.Property<string>("WorkloadKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("workload_key");

                    b.HasKey("Id")
                        .HasName("pk_incident_digests");

                    b.HasIndex("DigestHash")
                        .HasDatabaseName("ix_incident_digests_digest_hash");

                    b.HasIndex("IncidentId")
                        .IsUnique()
                        .HasDatabaseName("ix_incident_digests_incident_id");

                    b.HasIndex("WorkloadKey")
                        .HasDatabaseName("ix_incident_digests_workload_key");

                    b.ToTable("incident_digests", (string)null);
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.IncidentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("From")
                        .HasColumnType("text")
                        .HasColumnName("from");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to");

                    b.Property<string>("TraceId")
                        .HasColumnType("text")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_incident_events");

                    b.HasIndex("IncidentId", "At")
                        .HasDatabaseName("ix_incident_events_incident_id_at");

                    b.ToTable("incident_events", (string)null);
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.Investigation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<decimal>("CostUsd")
                        .HasColumnType("numeric(14,6)")
                        .HasColumnName("cost_usd");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("input_tokens");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_id");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("output_tokens");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("StepsUsed")
                        .HasColumnType("integer")
                        .HasColumnName("steps_used");

                    b.Property<string>("TerminationReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("termination_reason");

                    b.Property<int>("ToolCallsUsed")
                        .HasColumnType("integer")
                        .HasColumnName("tool_calls_used");

                    b.Property<string>("TraceId")
                        .HasColumnType("text")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_investigations");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("ix_investigations_incident_id");

                    b.HasIndex("StartedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_investigations_started_at");

                    b.HasIndex("TraceId")
                        .HasDatabaseName("ix_investigations_trace_id");

                    b.ToTable("investigations", (string)null);
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.InvestigationStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Arguments")
                        .HasColumnType("jsonb")
                        .HasColumnName("arguments");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<decimal>("CostUsd")
                        .HasColumnType("numeric(14,6)")
                        .HasColumnName("cost_usd");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<bool>("Failed")
                        .HasColumnType("boolean")
                        .HasColumnName("failed");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("input_tokens");

                    b.Property<Guid>("InvestigationId")
                        .HasColumnType("uuid")
                        .HasColumnName("investigation_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("output_tokens");

                    b.Property<Guid?>("RawBlobId")
                        .HasColumnType("uuid")
                        .HasColumnName("raw_blob_id");

                    b.Property<int>("ResultBytes")
                        .HasColumnType("integer")
                        .HasColumnName("result_bytes");

                    b.Property<string>("ResultDigest")
                        .HasColumnType("text")
                        .HasColumnName("result_digest");

                    b.Property<bool>("ResultTruncated")
                        .HasColumnType("boolean")
                        .HasColumnName("result_truncated");

                    b.Property<string>("ToolName")
                        .HasColumnType("text")
                        .HasColumnName("tool_name");

                    b.Property<string>("ToolServer")
                        .HasColumnType("text")
                        .HasColumnName("tool_server");

                    b.HasKey("Id")
                        .HasName("pk_investigation_steps");

                    b.HasIndex("InvestigationId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_investigation_steps_investigation_id_ordinal");

                    b.ToTable("investigation_steps", (string)null);
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.Signal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fingerprint");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Labels")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("labels");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("RawPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_signals");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("ix_signals_incident_id");

                    b.HasIndex("Labels")
                        .HasDatabaseName("ix_signals_labels_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Labels"), "gin");

                    b.HasIndex("Fingerprint", "LastSeen")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_signals_fingerprint_last_seen");

                    b.ToTable("signals", (string)null);
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.Verification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("uuid")
                        .HasColumnName("action_id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<string>("Checks")
                        .HasColumnType("jsonb")
                        .HasColumnName("checks");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<DateTimeOffset?>("RanAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ran_at");

                    b.HasKey("Id")
                        .HasName("pk_verifications");

                    b.HasIndex("ActionId", "Attempt")
                        .IsUnique()
                        .HasDatabaseName("ix_verifications_action_id_attempt");

                    b.HasIndex("DueAt", "Outcome")
                        .HasDatabaseName("ix_verifications_due_at_outcome");

                    b.ToTable("verifications", (string)null);
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.ActionPlan", b =>
                {
                    b.HasOne("Hephaisto.Core.Domain.Investigation", "Investigation")
                        .WithOne("Plan")
                        .HasForeignKey("Hephaisto.Core.Domain.ActionPlan", "InvestigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_action_plans_investigations_investigation_id");

                    b.Navigation("Investigation");
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.AgentAction", b =>
                {
                    b.HasOne("Hephaisto.Core.Domain.ActionPlan", "ActionPlan")
                        .WithMany("Actions")
                        .HasForeignKey("ActionPlanId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_agent_actions_action_plans_action_plan_id");

                    b.HasOne("Hephaisto.Core.Domain.Incident", "Incident")
                        .WithMany("Actions")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_actions_incidents_incident_id");

                    b.OwnsOne("Hephaisto.Core.Domain.TargetRef", "Target", b1 =>
                        {
                            b1.Property<Guid>("AgentActionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("target_kind");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("target_name");

                            b1.Property<string>("Namespace")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("target_namespace");

                            b1.Property<string>("NodeName")
                                .HasColumnType("text")
                                .HasColumnName("target_node_name");

                            b1.Property<string>("OwnerKind")
                                .HasColumnType("text")
                                .HasColumnName("target_owner_kind");

                            b1.Property<string>("OwnerName")
                                .HasColumnType("text")
                                .HasColumnName("target_owner_name");

                            b1.Property<string>("Uid")
                                .HasColumnType("text")
                                .HasColumnName("target_uid");

                            b1.HasKey("AgentActionId")
                                .HasName("pk_agent_actions");

                            b1.ToTable("agent_actions");

                            b1.WithOwner()
                                .HasForeignKey("AgentActionId")
                                .HasConstraintName("fk_agent_actions_agent_actions_agentactionid");
                        });

                    b.Navigation("ActionPlan");

                    b.Navigation("Incident");

                    b.Navigation("Target")
                        .IsRequired();
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.Evidence", b =>
                {
                    b.HasOne("Hephaisto.Core.Domain.Finding", "Finding")
                        .WithMany("Evidence")
                        .HasForeignKey("FindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_evidence_findings_finding_id");

                    b.HasOne("Hephaisto.Core.Domain.InvestigationStep", null)
                        .WithMany()
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_evidence_investigation_steps_step_id");

                    b.Navigation("Finding");
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.EvidenceBlob", b =>
                {
                    b.HasOne("Hephaisto.Core.Domain.Investigation", null)
                        .WithMany()
                        .HasForeignKey("InvestigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_evidence_blobs_investigations_investigation_id");
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.Finding", b =>
                {
                    b.HasOne("Hephaisto.Core.Domain.Investigation", "Investigation")
                        .WithMany("Findings")
                        .HasForeignKey("InvestigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_findings_investigations_investigation_id");

                    b.Navigation("Investigation");
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.HumanFeedback", b =>
                {
                    b.HasOne("Hephaisto.Core.Domain.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_human_feedback_incidents_incident_id");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.Incident", b =>
                {
                    b.OwnsOne("Hephaisto.Core.Domain.TargetRef", "Target", b1 =>
                        {
                            b1.Property<Guid>("IncidentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("target_kind");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("target_name");

                            b1.Property<string>("Namespace")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("target_namespace");

                            b1.Property<string>("NodeName")
                                .HasColumnType("text")
                                .HasColumnName("target_node_name");

                            b1.Property<string>("OwnerKind")
                                .HasColumnType("text")
                                .HasColumnName("target_owner_kind");

                            b1.Property<string>("OwnerName")
                                .HasColumnType("text")
                                .HasColumnName("target_owner_name");

                            b1.Property<string>("Uid")
                                .HasColumnType("text")
                                .HasColumnName("target_uid");

                            b1.HasKey("IncidentId")
                                .HasName("pk_incidents");

                            b1.ToTable("incidents");

                            b1.WithOwner()
                                .HasForeignKey("IncidentId")
                                .HasConstraintName("fk_incidents_incidents_incidentid");
                        });

                    b.Navigation("Target")
                        .IsRequired();
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.IncidentDigest", b =>
                {
                    b.HasOne("Hephaisto.Core.Domain.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incident_digests_incidents_incident_id");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.IncidentEvent", b =>
                {
                    b.HasOne("Hephaisto.Core.Domain.Incident", "Incident")
                        .WithMany("Events")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_incident_events_incidents_incident_id");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.Investigation", b =>
                {
                    b.HasOne("Hephaisto.Core.Domain.Incident", "Incident")
                        .WithMany("Investigations")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_investigations_incidents_incident_id");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.InvestigationStep", b =>
                {
                    b.HasOne("Hephaisto.Core.Domain.Investigation", "Investigation")
                        .WithMany("Steps")
                        .HasForeignKey("InvestigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_investigation_steps_investigations_investigation_id");

                    b.Navigation("Investigation");
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.Signal", b =>
                {
                    b.HasOne("Hephaisto.Core.Domain.Incident", "Incident")
                        .WithMany("Signals")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_signals_incidents_incident_id");

                    b.OwnsOne("Hephaisto.Core.Domain.TargetRef", "Target", b1 =>
                        {
                            b1.Property<Guid>("SignalId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("target_kind");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("target_name");

                            b1.Property<string>("Namespace")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("target_namespace");

                            b1.Property<string>("NodeName")
                                .HasColumnType("text")
                                .HasColumnName("target_node_name");

                            b1.Property<string>("OwnerKind")
                                .HasColumnType("text")
                                .HasColumnName("target_owner_kind");

                            b1.Property<string>("OwnerName")
                                .HasColumnType("text")
                                .HasColumnName("target_owner_name");

                            b1.Property<string>("Uid")
                                .HasColumnType("text")
                                .HasColumnName("target_uid");

                            b1.HasKey("SignalId")
                                .HasName("pk_signals");

                            b1.ToTable("signals");

                            b1.WithOwner()
                                .HasForeignKey("SignalId")
                                .HasConstraintName("fk_signals_signals_signalid");
                        });

                    b.Navigation("Incident");

                    b.Navigation("Target")
                        .IsRequired();
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.Verification", b =>
                {
                    b.HasOne("Hephaisto.Core.Domain.AgentAction", "Action")
                        .WithMany("Verifications")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verifications_agent_actions_action_id");

                    b.Navigation("Action");
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.ActionPlan", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.AgentAction", b =>
                {
                    b.Navigation("Verifications");
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.Finding", b =>
                {
                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.Incident", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Events");

                    b.Navigation("Investigations");

                    b.Navigation("Signals");
                });

            modelBuilder.Entity("Hephaisto.Core.Domain.Investigation", b =>
                {
                    b.Navigation("Findings");

                    b.Navigation("Plan");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
